CREATE TABLE IF NOT EXISTS roles (
  id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE,
  descripcion VARCHAR(180),
  permisos JSONB NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT roles_nombre_check
    CHECK (nombre IN ('ADMINISTRADOR', 'OPERADOR', 'CONDUCTOR')),
  CONSTRAINT roles_permisos_check
    CHECK (jsonb_typeof(permisos) = 'array')
);

CREATE TABLE IF NOT EXISTS personas (
  id_persona INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento VARCHAR(10) NOT NULL,
  nro_documento VARCHAR(15) NOT NULL UNIQUE,
  nombres VARCHAR(80) NOT NULL,
  apellidos VARCHAR(80) NOT NULL,
  telefono VARCHAR(20),
  email VARCHAR(150),
  direccion VARCHAR(180),
  tipo VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT personas_tipo_documento_check
    CHECK (tipo_documento IN ('DNI', 'RUC', 'CE')),
  CONSTRAINT personas_documento_check
    CHECK (nro_documento ~ '^[A-Za-z0-9-]{6,15}$'),
  CONSTRAINT personas_tipo_check
    CHECK (tipo IN ('CLIENTE', 'CONDUCTOR', 'EMPLEADO')),
  CONSTRAINT personas_telefono_check
    CHECK (telefono IS NULL OR telefono ~ '^[0-9+ -]{7,20}$'),
  CONSTRAINT personas_email_check
    CHECK (email IS NULL OR email = LOWER(email))
);

CREATE UNIQUE INDEX IF NOT EXISTS personas_email_unique
  ON personas (LOWER(email))
  WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  id_persona INTEGER UNIQUE REFERENCES personas(id_persona) ON DELETE SET NULL,
  id_rol INTEGER NOT NULL REFERENCES roles(id_rol),
  estado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  password_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT usuarios_username_check
    CHECK (username ~ '^[a-z0-9._-]{3,50}$'),
  CONSTRAINT usuarios_password_hash_check
    CHECK (LENGTH(password_hash) >= 50),
  CONSTRAINT usuarios_estado_check
    CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_username_unique
  ON usuarios (LOWER(username));

CREATE TABLE IF NOT EXISTS sesiones (
  token_hash CHAR(64) PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_hash CHAR(64),
  user_agent VARCHAR(255),
  revoked_at TIMESTAMPTZ,
  CONSTRAINT sesiones_expiry_check CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS sesiones_usuario_idx
  ON sesiones (id_usuario, expires_at DESC);
CREATE INDEX IF NOT EXISTS sesiones_expiry_idx
  ON sesiones (expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS rutas (
  id_ruta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origen VARCHAR(80) NOT NULL,
  destino VARCHAR(80) NOT NULL,
  distancia_km NUMERIC(7,2) NOT NULL,
  duracion_horas NUMERIC(5,2) NOT NULL,
  precio_base NUMERIC(10,2) NOT NULL,
  estado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT rutas_distancia_check CHECK (distancia_km > 0),
  CONSTRAINT rutas_duracion_check CHECK (duracion_horas > 0),
  CONSTRAINT rutas_precio_check CHECK (precio_base >= 0),
  CONSTRAINT rutas_estado_check CHECK (estado IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT rutas_origen_destino_unique UNIQUE (origen, destino)
);

CREATE TABLE IF NOT EXISTS vehiculos (
  id_vehiculo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placa VARCHAR(10) NOT NULL UNIQUE,
  tipo VARCHAR(50) NOT NULL,
  marca VARCHAR(40) NOT NULL,
  modelo VARCHAR(50) NOT NULL,
  capacidad INTEGER NOT NULL,
  anio INTEGER,
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT vehiculos_placa_check
    CHECK (placa ~ '^[A-Z0-9-]{5,10}$'),
  CONSTRAINT vehiculos_capacidad_check CHECK (capacidad BETWEEN 1 AND 80),
  CONSTRAINT vehiculos_anio_check CHECK (anio IS NULL OR anio BETWEEN 1990 AND 2100),
  CONSTRAINT vehiculos_estado_check
    CHECK (estado IN ('ACTIVO', 'MANTENIMIENTO', 'DE_BAJA'))
);

CREATE TABLE IF NOT EXISTS conductores (
  id_conductor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_persona INTEGER NOT NULL UNIQUE REFERENCES personas(id_persona) ON DELETE RESTRICT,
  nro_licencia VARCHAR(20) NOT NULL UNIQUE,
  categoria_licencia VARCHAR(10) NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  habilitado BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS viajes (
  id_viaje INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta INTEGER NOT NULL REFERENCES rutas(id_ruta) ON DELETE RESTRICT,
  id_vehiculo INTEGER NOT NULL REFERENCES vehiculos(id_vehiculo) ON DELETE RESTRICT,
  id_conductor INTEGER NOT NULL REFERENCES conductores(id_conductor) ON DELETE RESTRICT,
  fecha_hora_salida TIMESTAMPTZ NOT NULL,
  fecha_hora_llegada TIMESTAMPTZ,
  precio_final NUMERIC(10,2) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADO',
  request_id UUID UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT viajes_precio_check CHECK (precio_final >= 0),
  CONSTRAINT viajes_fechas_check
    CHECK (fecha_hora_llegada IS NULL OR fecha_hora_llegada > fecha_hora_salida),
  CONSTRAINT viajes_estado_check
    CHECK (estado IN ('PROGRAMADO', 'EN_CURSO', 'COMPLETADO', 'CANCELADO')),
  CONSTRAINT viajes_vehiculo_salida_unique UNIQUE (id_vehiculo, fecha_hora_salida),
  CONSTRAINT viajes_conductor_salida_unique UNIQUE (id_conductor, fecha_hora_salida)
);

CREATE INDEX IF NOT EXISTS viajes_salida_idx
  ON viajes (fecha_hora_salida, estado);
CREATE INDEX IF NOT EXISTS viajes_conductor_idx
  ON viajes (id_conductor, fecha_hora_salida);

CREATE TABLE IF NOT EXISTS boletos (
  id_boleto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  id_viaje INTEGER NOT NULL REFERENCES viajes(id_viaje) ON DELETE RESTRICT,
  id_persona_pasajero INTEGER NOT NULL REFERENCES personas(id_persona) ON DELETE RESTRICT,
  asiento INTEGER NOT NULL,
  precio NUMERIC(10,2) NOT NULL,
  estado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  comprobante_serie VARCHAR(10),
  comprobante_numero VARCHAR(15),
  sunat_estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  request_id UUID UNIQUE,
  anulado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  anulado_at TIMESTAMPTZ,
  CONSTRAINT boletos_asiento_check CHECK (asiento BETWEEN 1 AND 80),
  CONSTRAINT boletos_precio_check CHECK (precio >= 0),
  CONSTRAINT boletos_estado_check CHECK (estado IN ('ACTIVO', 'ANULADO')),
  CONSTRAINT boletos_sunat_check
    CHECK (sunat_estado IN ('PENDIENTE', 'ACEPTADO', 'RECHAZADO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS boletos_viaje_asiento_activo_unique
  ON boletos (id_viaje, asiento)
  WHERE estado = 'ACTIVO';
CREATE INDEX IF NOT EXISTS boletos_viaje_idx
  ON boletos (id_viaje, estado);

CREATE TABLE IF NOT EXISTS encomiendas (
  id_encomienda INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_tracking VARCHAR(25) NOT NULL UNIQUE,
  id_viaje INTEGER NOT NULL REFERENCES viajes(id_viaje) ON DELETE RESTRICT,
  id_persona_remitente INTEGER NOT NULL REFERENCES personas(id_persona) ON DELETE RESTRICT,
  id_persona_destinatario INTEGER NOT NULL REFERENCES personas(id_persona) ON DELETE RESTRICT,
  peso_kg NUMERIC(8,2) NOT NULL,
  dimensiones VARCHAR(60),
  descripcion VARCHAR(240) NOT NULL,
  valor_declarado NUMERIC(12,2) NOT NULL DEFAULT 0,
  costo NUMERIC(10,2) NOT NULL,
  estado VARCHAR(25) NOT NULL DEFAULT 'REGISTRADO',
  fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  request_id UUID UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT encomiendas_peso_check CHECK (peso_kg > 0 AND peso_kg <= 1000),
  CONSTRAINT encomiendas_valor_check CHECK (valor_declarado >= 0),
  CONSTRAINT encomiendas_costo_check CHECK (costo >= 0),
  CONSTRAINT encomiendas_estado_check
    CHECK (estado IN (
      'REGISTRADO',
      'RECOJO_DOMICILIO',
      'EN_TRANSITO',
      'EN_DESTINO',
      'ENTREGADO'
    ))
);

CREATE INDEX IF NOT EXISTS encomiendas_tracking_idx
  ON encomiendas (codigo_tracking);
CREATE INDEX IF NOT EXISTS encomiendas_viaje_idx
  ON encomiendas (id_viaje, estado);

CREATE TABLE IF NOT EXISTS tracking_encomiendas (
  id_tracking INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_encomienda INTEGER NOT NULL REFERENCES encomiendas(id_encomienda) ON DELETE CASCADE,
  estado VARCHAR(25) NOT NULL,
  ubicacion VARCHAR(180) NOT NULL,
  latitude NUMERIC(9,6),
  longitude NUMERIC(9,6),
  id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  fecha_hora TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  observacion VARCHAR(300),
  evidencia JSONB,
  request_id UUID UNIQUE,
  CONSTRAINT tracking_estado_check
    CHECK (estado IN (
      'REGISTRADO',
      'RECOJO_DOMICILIO',
      'EN_TRANSITO',
      'EN_DESTINO',
      'ENTREGADO'
    )),
  CONSTRAINT tracking_latitude_check
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT tracking_longitude_check
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  CONSTRAINT tracking_evidencia_check
    CHECK (evidencia IS NULL OR jsonb_typeof(evidencia) = 'object')
);

CREATE INDEX IF NOT EXISTS tracking_encomienda_fecha_idx
  ON tracking_encomiendas (id_encomienda, fecha_hora DESC);

CREATE TABLE IF NOT EXISTS solicitudes_recojo (
  id_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_persona INTEGER NOT NULL REFERENCES personas(id_persona) ON DELETE RESTRICT,
  direccion VARCHAR(180) NOT NULL,
  telefono_contacto VARCHAR(20) NOT NULL,
  fecha_solicitada DATE NOT NULL,
  descripcion VARCHAR(240) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  id_usuario_asignado INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  request_id UUID UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT recojos_telefono_check
    CHECK (telefono_contacto ~ '^[0-9+ -]{7,20}$'),
  CONSTRAINT recojos_estado_check
    CHECK (estado IN ('PENDIENTE', 'ASIGNADO', 'COMPLETADO', 'CANCELADO'))
);

CREATE INDEX IF NOT EXISTS recojos_estado_fecha_idx
  ON solicitudes_recojo (estado, fecha_solicitada);

CREATE TABLE IF NOT EXISTS notificaciones (
  id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(15) NOT NULL,
  destinatario VARCHAR(150) NOT NULL,
  mensaje TEXT NOT NULL,
  estado_envio VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  fecha_envio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT notificaciones_tipo_check CHECK (tipo IN ('SMS', 'WHATSAPP', 'EMAIL')),
  CONSTRAINT notificaciones_estado_check
    CHECK (estado_envio IN ('PENDIENTE', 'ENVIADO', 'ERROR'))
);

CREATE TABLE IF NOT EXISTS rate_limits (
  rate_key VARCHAR(180) NOT NULL,
  bucket_start BIGINT NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (rate_key, bucket_start),
  CONSTRAINT rate_limits_count_check CHECK (request_count > 0)
);

CREATE INDEX IF NOT EXISTS rate_limits_expiry_idx
  ON rate_limits (expires_at);

CREATE TABLE IF NOT EXISTS audit_logs (
  id_audit BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  accion VARCHAR(80) NOT NULL,
  entidad VARCHAR(50) NOT NULL,
  entidad_id VARCHAR(80),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip_hash CHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT audit_metadata_check CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS audit_logs_usuario_fecha_idx
  ON audit_logs (id_usuario, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entidad_idx
  ON audit_logs (entidad, entidad_id, created_at DESC);
