ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_nombre_check;
ALTER TABLE roles
  ADD CONSTRAINT roles_nombre_check
  CHECK (nombre IN ('SUPER_ADMIN', 'ADMINISTRADOR', 'OPERADOR', 'CONDUCTOR'));

INSERT INTO roles (nombre, descripcion, permisos)
VALUES (
  'SUPER_ADMIN',
  'Administración global de todas las agencias',
  '["agencias:*", "usuarios:*", "operaciones:*", "reportes:*"]'::jsonb
)
ON CONFLICT (nombre) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    permisos = EXCLUDED.permisos;

CREATE TABLE IF NOT EXISTS agencias (
  id_agencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  ciudad VARCHAR(80) NOT NULL,
  direccion VARCHAR(180) NOT NULL,
  telefono VARCHAR(20),
  email VARCHAR(150),
  estado VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT agencias_codigo_check
    CHECK (codigo ~ '^[A-Z0-9-]{2,20}$'),
  CONSTRAINT agencias_estado_check
    CHECK (estado IN ('ACTIVA', 'INACTIVA')),
  CONSTRAINT agencias_telefono_check
    CHECK (telefono IS NULL OR telefono ~ '^[0-9+ -]{7,20}$'),
  CONSTRAINT agencias_email_check
    CHECK (email IS NULL OR email = LOWER(email))
);

CREATE UNIQUE INDEX IF NOT EXISTS agencias_nombre_ciudad_unique
  ON agencias (LOWER(nombre), LOWER(ciudad));

INSERT INTO agencias (codigo, nombre, ciudad, direccion)
VALUES ('AYA', 'Agencia Ayacucho', 'Ayacucho', 'Dirección por configurar')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    ciudad = EXCLUDED.ciudad,
    updated_at = NOW();

INSERT INTO agencias (codigo, nombre, ciudad, direccion)
SELECT DISTINCT
  'AG-' || UPPER(SUBSTRING(MD5(LOWER(TRIM(destino))) FROM 1 FOR 8)),
  'Agencia ' || TRIM(destino),
  TRIM(destino),
  'Dirección por configurar'
FROM rutas
WHERE LOWER(TRIM(destino)) <> 'ayacucho'
ON CONFLICT (codigo) DO NOTHING;

CREATE TABLE IF NOT EXISTS usuarios_agencias (
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  id_agencia INTEGER NOT NULL REFERENCES agencias(id_agencia) ON DELETE RESTRICT,
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  estado VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_usuario, id_agencia),
  CONSTRAINT usuarios_agencias_estado_check
    CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_agencias_principal_unique
  ON usuarios_agencias (id_usuario)
  WHERE es_principal = TRUE AND estado = 'ACTIVO';
CREATE INDEX IF NOT EXISTS usuarios_agencias_agencia_idx
  ON usuarios_agencias (id_agencia, estado);

INSERT INTO usuarios_agencias (id_usuario, id_agencia, es_principal)
SELECT u.id_usuario, a.id_agencia, TRUE
FROM usuarios u
CROSS JOIN agencias a
WHERE a.codigo = 'AYA'
ON CONFLICT (id_usuario, id_agencia) DO NOTHING;

ALTER TABLE rutas
  ADD COLUMN IF NOT EXISTS id_agencia_origen INTEGER REFERENCES agencias(id_agencia),
  ADD COLUMN IF NOT EXISTS id_agencia_destino INTEGER REFERENCES agencias(id_agencia);

UPDATE rutas route
SET id_agencia_origen = agency.id_agencia
FROM agencias agency
WHERE route.id_agencia_origen IS NULL
  AND agency.codigo = 'AYA';

UPDATE rutas route
SET id_agencia_destino = agency.id_agencia
FROM agencias agency
WHERE route.id_agencia_destino IS NULL
  AND (
    LOWER(agency.ciudad) = LOWER(TRIM(route.destino))
    OR LOWER(agency.nombre) = LOWER('Agencia ' || TRIM(route.destino))
  );

ALTER TABLE rutas
  ALTER COLUMN id_agencia_origen SET NOT NULL,
  ALTER COLUMN id_agencia_destino SET NOT NULL;

CREATE INDEX IF NOT EXISTS rutas_agencias_idx
  ON rutas (id_agencia_origen, id_agencia_destino, estado);

ALTER TABLE vehiculos
  ADD COLUMN IF NOT EXISTS id_agencia_base INTEGER REFERENCES agencias(id_agencia);
UPDATE vehiculos
SET id_agencia_base = (
  SELECT id_agencia FROM agencias WHERE codigo = 'AYA'
)
WHERE id_agencia_base IS NULL;
ALTER TABLE vehiculos ALTER COLUMN id_agencia_base SET NOT NULL;
CREATE INDEX IF NOT EXISTS vehiculos_agencia_idx
  ON vehiculos (id_agencia_base, estado);

ALTER TABLE conductores
  ADD COLUMN IF NOT EXISTS id_agencia_base INTEGER REFERENCES agencias(id_agencia);
UPDATE conductores
SET id_agencia_base = (
  SELECT id_agencia FROM agencias WHERE codigo = 'AYA'
)
WHERE id_agencia_base IS NULL;
ALTER TABLE conductores ALTER COLUMN id_agencia_base SET NOT NULL;
CREATE INDEX IF NOT EXISTS conductores_agencia_idx
  ON conductores (id_agencia_base, habilitado);

ALTER TABLE viajes
  ADD COLUMN IF NOT EXISTS id_agencia INTEGER REFERENCES agencias(id_agencia);
UPDATE viajes trip
SET id_agencia = route.id_agencia_origen
FROM rutas route
WHERE trip.id_ruta = route.id_ruta
  AND trip.id_agencia IS NULL;
ALTER TABLE viajes ALTER COLUMN id_agencia SET NOT NULL;
CREATE INDEX IF NOT EXISTS viajes_agencia_salida_idx
  ON viajes (id_agencia, fecha_hora_salida, estado);

ALTER TABLE boletos
  ADD COLUMN IF NOT EXISTS id_agencia_venta INTEGER REFERENCES agencias(id_agencia);
UPDATE boletos ticket
SET id_agencia_venta = trip.id_agencia
FROM viajes trip
WHERE ticket.id_viaje = trip.id_viaje
  AND ticket.id_agencia_venta IS NULL;
ALTER TABLE boletos ALTER COLUMN id_agencia_venta SET NOT NULL;
CREATE INDEX IF NOT EXISTS boletos_agencia_fecha_idx
  ON boletos (id_agencia_venta, fecha_emision DESC);

ALTER TABLE encomiendas
  ADD COLUMN IF NOT EXISTS id_agencia_registro INTEGER REFERENCES agencias(id_agencia);
UPDATE encomiendas parcel
SET id_agencia_registro = trip.id_agencia
FROM viajes trip
WHERE parcel.id_viaje = trip.id_viaje
  AND parcel.id_agencia_registro IS NULL;
ALTER TABLE encomiendas ALTER COLUMN id_agencia_registro SET NOT NULL;
CREATE INDEX IF NOT EXISTS encomiendas_agencia_fecha_idx
  ON encomiendas (id_agencia_registro, fecha_registro DESC);

ALTER TABLE solicitudes_recojo
  ADD COLUMN IF NOT EXISTS id_agencia INTEGER REFERENCES agencias(id_agencia);
UPDATE solicitudes_recojo
SET id_agencia = (
  SELECT id_agencia FROM agencias WHERE codigo = 'AYA'
)
WHERE id_agencia IS NULL;
ALTER TABLE solicitudes_recojo ALTER COLUMN id_agencia SET NOT NULL;
CREATE INDEX IF NOT EXISTS recojos_agencia_estado_idx
  ON solicitudes_recojo (id_agencia, estado, fecha_solicitada);

ALTER TABLE notificaciones
  ADD COLUMN IF NOT EXISTS id_agencia INTEGER REFERENCES agencias(id_agencia);
ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS id_agencia INTEGER REFERENCES agencias(id_agencia);
ALTER TABLE sesiones
  ADD COLUMN IF NOT EXISTS id_agencia_activa INTEGER REFERENCES agencias(id_agencia);

UPDATE sesiones session
SET id_agencia_activa = membership.id_agencia
FROM usuarios_agencias membership
WHERE membership.id_usuario = session.id_usuario
  AND membership.es_principal = TRUE
  AND membership.estado = 'ACTIVO'
  AND session.id_agencia_activa IS NULL;

CREATE INDEX IF NOT EXISTS sesiones_agencia_idx
  ON sesiones (id_agencia_activa, expires_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_agencia_fecha_idx
  ON audit_logs (id_agencia, created_at DESC);
