CREATE TABLE IF NOT EXISTS incidencias_viajes (
  id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_viaje INTEGER NOT NULL REFERENCES viajes(id_viaje) ON DELETE CASCADE,
  id_conductor INTEGER NOT NULL REFERENCES conductores(id_conductor) ON DELETE RESTRICT,
  id_agencia INTEGER NOT NULL REFERENCES agencias(id_agencia) ON DELETE RESTRICT,
  id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  tipo VARCHAR(40) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  nivel_gravedad VARCHAR(20) NOT NULL DEFAULT 'LEVE',
  latitude NUMERIC(9,6),
  longitude NUMERIC(9,6),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT incidencias_tipo_check
    CHECK (tipo IN ('MECANICA', 'CLIMA', 'BLOQUEO_VIA', 'ACCIDENTE', 'RETRASO', 'OTRO')),
  CONSTRAINT incidencias_gravedad_check
    CHECK (nivel_gravedad IN ('LEVE', 'MODERADA', 'GRAVE')),
  CONSTRAINT incidencias_lat_check
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT incidencias_lng_check
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS incidencias_viaje_idx
  ON incidencias_viajes (id_viaje, created_at DESC);
CREATE INDEX IF NOT EXISTS incidencias_agencia_idx
  ON incidencias_viajes (id_agencia, created_at DESC);
CREATE INDEX IF NOT EXISTS incidencias_conductor_idx
  ON incidencias_viajes (id_conductor, created_at DESC);
