ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS temporary_password_expires_at TIMESTAMPTZ;

ALTER TABLE usuarios
  DROP CONSTRAINT IF EXISTS usuarios_temporary_password_check;
ALTER TABLE usuarios
  ADD CONSTRAINT usuarios_temporary_password_check
  CHECK (
    (must_change_password = TRUE AND temporary_password_expires_at IS NOT NULL)
    OR
    (must_change_password = FALSE AND temporary_password_expires_at IS NULL)
  );

CREATE TABLE IF NOT EXISTS solicitudes_anulacion_boletos (
  id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_boleto INTEGER NOT NULL REFERENCES boletos(id_boleto) ON DELETE RESTRICT,
  id_agencia INTEGER NOT NULL REFERENCES agencias(id_agencia) ON DELETE RESTRICT,
  solicitado_por INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
  motivo_solicitud VARCHAR(300) NOT NULL,
  estado VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  resuelto_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
  motivo_resolucion VARCHAR(300),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT solicitudes_anulacion_estado_check
    CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
  CONSTRAINT solicitudes_anulacion_resolucion_check
    CHECK (
      (estado = 'PENDIENTE' AND resuelto_por IS NULL AND resolved_at IS NULL)
      OR
      (estado IN ('APROBADA', 'RECHAZADA') AND resuelto_por IS NOT NULL AND resolved_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS solicitudes_anulacion_boleto_pendiente_unique
  ON solicitudes_anulacion_boletos (id_boleto)
  WHERE estado = 'PENDIENTE';
CREATE INDEX IF NOT EXISTS solicitudes_anulacion_agencia_estado_idx
  ON solicitudes_anulacion_boletos (id_agencia, estado, requested_at DESC);

CREATE TABLE IF NOT EXISTS documentos_operativos (
  id_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_agencia INTEGER NOT NULL REFERENCES agencias(id_agencia) ON DELETE RESTRICT,
  titular_tipo VARCHAR(12) NOT NULL,
  id_conductor INTEGER REFERENCES conductores(id_conductor) ON DELETE CASCADE,
  id_vehiculo INTEGER REFERENCES vehiculos(id_vehiculo) ON DELETE CASCADE,
  tipo_documento VARCHAR(30) NOT NULL,
  numero VARCHAR(60) NOT NULL,
  fecha_emision DATE,
  fecha_vencimiento DATE NOT NULL,
  estado VARCHAR(15) NOT NULL DEFAULT 'VIGENTE',
  observacion VARCHAR(300),
  creado_por INTEGER REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT documentos_titular_check CHECK (
    (titular_tipo = 'CONDUCTOR' AND id_conductor IS NOT NULL AND id_vehiculo IS NULL)
    OR
    (titular_tipo = 'VEHICULO' AND id_vehiculo IS NOT NULL AND id_conductor IS NULL)
  ),
  CONSTRAINT documentos_tipo_check CHECK (
    tipo_documento IN (
      'LICENCIA', 'SOAT', 'CITV', 'TUC', 'TARJETA_PROPIEDAD',
      'ANTECEDENTES', 'SALUD', 'OTRO'
    )
  ),
  CONSTRAINT documentos_estado_check
    CHECK (estado IN ('VIGENTE', 'POR_VENCER', 'VENCIDO', 'OBSERVADO')),
  CONSTRAINT documentos_fechas_check
    CHECK (fecha_emision IS NULL OR fecha_vencimiento >= fecha_emision)
);

CREATE UNIQUE INDEX IF NOT EXISTS documentos_operativos_unique
  ON documentos_operativos (
    titular_tipo,
    COALESCE(id_conductor, 0),
    COALESCE(id_vehiculo, 0),
    tipo_documento,
    numero
  );
CREATE INDEX IF NOT EXISTS documentos_agencia_vencimiento_idx
  ON documentos_operativos (id_agencia, fecha_vencimiento, estado);

UPDATE roles
SET permisos = CASE nombre
  WHEN 'SUPER_ADMIN' THEN '["*"]'::jsonb
  WHEN 'ADMINISTRADOR' THEN '["agencia:administrar", "usuarios:administrar", "operaciones:administrar", "reportes:agencia", "flota:administrar"]'::jsonb
  WHEN 'OPERADOR' THEN '["pasajes:vender", "anulaciones:solicitar", "encomiendas:registrar", "recojos:registrar", "caja:hoy"]'::jsonb
  WHEN 'CONDUCTOR' THEN '["viajes:propios", "entregas:propias", "gps:publicar", "incidencias:crear"]'::jsonb
  ELSE permisos
END;
