-- Restores the retired TOTP schema only. Previously deleted secrets and
-- recovery codes cannot be reconstructed by a rollback.
ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS mfa_secret_encrypted TEXT,
  ADD COLUMN IF NOT EXISTS mfa_enrolled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS mfa_last_used_step BIGINT;

ALTER TABLE usuarios
  DROP CONSTRAINT IF EXISTS usuarios_mfa_state_check;
ALTER TABLE usuarios
  ADD CONSTRAINT usuarios_mfa_state_check
  CHECK (
    (mfa_enabled = TRUE AND mfa_secret_encrypted IS NOT NULL AND mfa_enrolled_at IS NOT NULL)
    OR
    (mfa_enabled = FALSE AND mfa_secret_encrypted IS NULL AND mfa_enrolled_at IS NULL)
  );

ALTER TABLE sesiones
  ADD COLUMN IF NOT EXISTS mfa_setup_secret_encrypted TEXT;

CREATE TABLE IF NOT EXISTS mfa_recovery_codes (
  id_recovery BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  code_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  used_at TIMESTAMPTZ,
  CONSTRAINT mfa_recovery_code_hash_check CHECK (code_hash ~ '^[a-f0-9]{64}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS mfa_recovery_codes_hash_unique
  ON mfa_recovery_codes (id_usuario, code_hash);
CREATE INDEX IF NOT EXISTS mfa_recovery_codes_active_idx
  ON mfa_recovery_codes (id_usuario, created_at DESC)
  WHERE used_at IS NULL;
